# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- basic-camera-app

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: src/app

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build -- --configuration accept
    workingDir: src/app
- task: Npm@1
  displayName: 'Test Angular'
  inputs:
    command: custom
    customCommand: test
    workingDir: src/app

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'src/www'